
name: deploy-lambda
env:
  S3_BUCKET_NAME                      : "github-actions-lambda"
  DEPLOY_PACKAGE_NAME                 : "github-actions-lambda.zip"
  AWS_REGION_NAME                     : "us-east-1"
  RUNNER_PYTHON_VERSION               : "3.8"
  PYTHON_ENV                          : "python3.8"
on:
  push:
    branches:
      - main

jobs:

  deploy-de-lambda:
    runs-on: ubuntu-latest

    steps:

      - name: install aws cli
        run: |
          pip3 install awscli


      - name: Configure AWS Credentils
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id     : ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region            : ${{ env.AWS_REGION_NAME }}

      - name: create DE deployment package
        uses: montudor/action-zip@v1
        with: 
          args: "zip -r ../${{ env.DEPLOY_PACKAGE_NAME }} ."
          
      - name: deploy  DE lambda
        run: |
          aws lambda update-function-code \
          --function-name "github-actions-on-lambda" \
          --zip-file ${{ env.DEPLOY_PACKAGE_NAME}}
          

    
  
  
  
  