
name: ReleaseCI
env:
  S3_BUCKET_NAME                      : "github-actions-lambda"
  DEPLOY_PACKAGE_NAME                 : "github-actions-lambda_$(date +%Y%m%d).zip"
  AWS_REGION_NAME                     : "ap-south-1"
  RUNNER_PYTHON_VERSION               : "3.8"
  PYTHON_ENV                          : "python3.8"
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Release to S3
      run: bash scripts/pipeline/release.sh ${{env.S3_BUCKET_NAME}} "folder1/myapp.zip"  ${{secrets.AWS_ACCESS_KEY_ID}} ${{secrets.AWS_SECRET_ACCESS_KEY}} "myapp.zip"